//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobTrackingForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int Ticket_Numarası { get; set; }
        public string Müşteri { get; set; }
        public string Konu { get; set; }
        public string Açıklama { get; set; }
        public string Üst_Açıklama { get; set; }
        public string Sorumlu { get; set; }
        public Nullable<System.DateTime> Planlama_Tarihi { get; set; }
        public Nullable<System.DateTime> Tamamlama_Tarihi { get; set; }
        public string Durum { get; set; }
    }
}
